src/Entity/Book.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookRepository")
 */
class Book
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="boolean")
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $autor;

    /**
     * @ORM\Column(type="text")
     */
    private $resume;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category",cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="books")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Library", inversedBy="books")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Library;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getAutor(): ?string
    {
        return $this->autor;
    }

    public function setAutor(string $autor): self
    {
        $this->autor = $autor;

        return $this;
    }

    public function getExtrait(): ?string
    {
        return substr($this->resume,0,50);
    }

    public function getResume(): ?string
    {
        return $this->resume;
    }

    public function setResume(string $resume): self
    {
        $this->resume = $resume;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;
        if($user)
        {
            $this->setStatus(0);
        }
        else
        {
            $this->setStatus(1);
        }
        return $this;
    }

    public function getLibrary(): ?Library
    {
        return $this->Library;
    }

    public function setLibrary(?Library $Library): self
    {
        $this->Library = $Library;

        return $this;
    }
}

src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Book;
use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, ['label' => 'name'])
            ->add('status', ChoiceType::class, ['choices' => ['En stock' => 1 , 'Indisponible' => 0]])
            ->add('autor', TextType::class, ['label' => 'autor'])
            ->add('resume', TextType::class, ['label' => 'resume'])
            ->add('date', DateType::class, ['label' => 'date'])
            ->add('category', EntityType::class, 
            [
                'class' => Category::class,
                'choice_label' => 'categoryName',
            ])
            ->add('Envoyer', SubmitType::class, 
            [
                'attr' => 
                [
                    'label' => 'Envoyer'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
        [
            'data_class' => Book::class,
        ]);
    }
}

src/Controller/BookController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Book;
use App\Entity\User;
use App\Form\BookType;
use App\Form\SortByType;
use App\Form\BorrowType;
use App\Repository\BookRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
* Require ROLE_ADMIN for *every* controller method in this class.
*
* @IsGranted("ROLE_ADMIN")
*/
class BookController extends AbstractController
{

  /**
  * @Route("/listbook", name="book_index", methods={"GET","POST"})
  * @Route("/listbook")
  */

  public function home(BookRepository $bookRepository, Request $request): Response
  {
    $form = $this->createForm(SortByType::class);
    $form->handleRequest($request);
    
    if ($form->isSubmitted() && $form->isValid())
    {
      $categorySearch = $form->getData();
      $books = $bookRepository->getBookWithCategory($categorySearch['categoryName']);
    }

    else
    {
      $books = $bookRepository->findAll();
    }

    return $this->render('book/index.html.twig',
    [
      'book' => $books,
      'form' => $form->createView()
    ]);
  }

  /**
  * Matches @Route("/single/{id}", requirements={"id"="\d+"}) exactly
  * @Route("/single/{id}", requirements={"id"="\d+"}, name="book_single")
  */

  public function single($id, Request $request)
  {
    $book = $this->getDoctrine()->getRepository(Book::class)->findBookAndUser($id);
    
    if(!$book)
    {
      throw $this->createNotFoundException("Ce livre n'existe pas");
    }

    $form = $this->createForm(BorrowType::class);
    $form->handleRequest($request);
    
    if ($form->isSubmitted() && $form->isValid())
    {
      $data = $form->getData();
      $user = $this->getDoctrine()->getRepository(User::class)->findOneBy(["code" => $data["code"]]);
      
      if(!$user)
      {
        $this->addFlash("danger", "Ce code utilisateur n'est pas valide");
      }

      else
      {
        $book->setUser($user);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($book);
        $entityManager->flush();
        $this->addFlash("success", "Le livre a été emprunté");
      }
    }

    return $this->render('book/single.html.twig',
    [
      'book' => $book,
      'form' => $form->createView()
    ]);
  }
  
  /**
  * @Route("/addbook", name="book_new", methods={"GET","POST"})
  */

  public function new(Request $request): Response
  {
    $book = new Book();
    $form = $this->createForm(BookType::class, $book);
    $form->handleRequest($request);
    
    if ($form->isSubmitted() && $form->isValid())
    {
      $entityManager = $this->getDoctrine()->getManager();
      $entityManager->persist($book);
      $entityManager->flush();  
      return $this->redirectToRoute('book_index');
    }
    
    return $this->render('book/addbook.html.twig',
    [
      'book' => $book,
      'form' => $form->createView()
    ]);
  }

  /**
  * @Route("back/{id}", name="book_retour")
  */
    public function retour(Book $book)
    {
      if($book->getStatus()) {
        $this->addFlash("danger", "Ce livre n'a jamais été emprunté");
      }
      else {
        $book->setUser(null);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($book);
        $entityManager->flush();
        $this->addFlash("success", "Le livre a été rendu");
      }
      return $this->redirectToRoute('book_single', ["id" => $book->getId()]);
    }
}

templates/book/addbook.html.twig
{% extends "base.html.twig" %}
{% block pageTitle %}
    Livre séléctionné
{% endblock %}

{% block body %}
    {{ form_start(form) }}

    {{ form_end(form) }}
{% endblock %}

templates/book/index.html.twig
{% extends "base.html.twig" %}

{% block pageTitle %}
  Liste des livres
{% endblock %}

{% block body %}
  {{ form_start(form) }}

  {{ form_end(form) }}
  <div class="container">
    <div class="row">
      <div class="container">
        <div class="row">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Nom</th>
                <th scope="col">Extrait</th>
                <th scope="col">Auteur</th>
                <th scope="col">Catégorie</th>
                <th scope="col">Date de sortie</th>
                <th scope="col">Loué par</th>
                <th scope="col">Voir le livre</th>
              </tr>
            </thead>
            <tbody>
              {% for books in book %}
                <tr>
                  <td>{{ books.name }}</td>
                  <td>{{ books.extrait }}</td>
                  <td>{{ books.autor }}</td>
                  <td>{{ books.category.categoryName }}</td>
                  <td>{{ books.date|date("d/m/Y") }}</td>
                  {% if books.user %}
                    <td><a href="user/{{ books.user.id }}"> {{ books.user.firstname }} {{ books.user.lastname }}</a></td>
                  {% else %}
                    <td>Personne</td>
                  {% endif %}
                  <td><a href="single/{{ books.id }}" class="card-link">Cliquez ici</a></td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/book/single.html.twig
{% extends "base.html.twig" %}

{% block pageTitle %}
  Livre séléctionné
{% endblock %}

{% block body %}
  <div class="container">
    <div class="row">
      <div class="container">
        <div class="row">
            <div class="col-12  my-3">
              <div class="card mb">
                <img class="card-img-top" src="https://www.image.ie/images/no-image.png" alt="Card image cap">
                <div class="card-body mb">
                  <h5 class="card-title">{{ book.name }}</h5>
                  <p class="card-text">{{ book.resume }}</p>
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item">Auteur: {{ book.autor }}</li>
                    <li class="list-group-item">Catégorie: {{ book.category.categoryName }}</li>
                    <li class="list-group-item">Publié le: {{ book.date|date("d/m/Y") }}</li>
                    <li class="list-group-item">Loué par:
                    {% if book.user %}
                      <td><a href="/user/{{ book.user.id }}"> {{ book.user.firstname }} {{ book.user.lastname }}</a></td>
                      <a href="{{ path("book_retour", {"id" : book.id})}}" class="btn btn-success">Retour livre</a>
                    {% else %}
                      <td>Personne</td>
                      {{ form_start(form) }}
                      {{ form_widget(form.code) }}
                      {{ form_widget(form.Emprunter) }}
                      {{ form_end(form) }}
                    {% endif %}
                  </ul>
            </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}